"""The Phase 0 step 4 rule-parity corpus must be what the engine says today.

tests/fixtures/engine_rule_corpus.json is generated by tools/engine_rule_corpus.py
from the Python engine and is what scripts/check-vehicle-engine-rules.ts holds
the TypeScript port to. If an engine rule changes without regenerating the
corpus, this fails -- the TypeScript side can never be checked against a stale
reference.
"""

from __future__ import annotations

from tools import engine_rule_corpus


def test_committed_corpus_matches_the_engine():
    expected = engine_rule_corpus.render(engine_rule_corpus.build())
    committed = engine_rule_corpus.CORPUS.read_text(encoding="utf-8")
    assert committed == expected, "run: python -m tools.engine_rule_corpus"


def test_corpus_covers_every_section_with_both_outcomes():
    corpus = engine_rule_corpus.build()
    for section in ("taxonomy", "price_parse", "campaign_parse", "registry", "price_planners", "sidecars"):
        outcomes = {case["ok"] for case in corpus[section]}
        assert outcomes == {True, False}, section
    assert any(case["problems"] for case in corpus["facts"])
    assert any(not case["problems"] for case in corpus["facts"])
    assert any(case["problems"] for case in corpus["resolution"])
    assert corpus["resolution"][0]["name"] == "repository catalog 2026"
    assert corpus["resolution"][0]["problems"] == []
    assert len(corpus["served"]) >= 5
