"""Render CALIBRATION_REPORT.md from the computed summary. All numbers come from `report.compute`; only the prose is written here."""
from __future__ import annotations

from . import review as RV
from . import report as RP


def table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|") for c in r) + " |")
    return "\n".join(out)


def kv(d: dict) -> str:
    return table(["value", "count"], [[k, v] for k, v in d.items()])


NEED_WORDS = {"OWNER DECISION": "an owner decision", "OWNER LABELS": "owner labels", "OWNER SIGN-OFF": "an owner sign-off",
              "ICE ANSWER (Q-ICE-ABSENT-ROW) + TDR GUARANTEE, THEN OWNER LABELS": "Ice's answer (Q-ICE-ABSENT-ROW) and a TDR guarantee, then owner labels"}


def render(s: dict) -> str:
    rec, win, mat, dist = s["recovery"], s["legacy_window"], s["material_change"], s["distributions"]
    out, sh, obs = s["v1_outcomes"], s["review_sheet"], s["data_observations"]
    ents = RP.entry_table(s)
    by_need: dict[str, int] = {}
    for e in ents:
        by_need[e["needs"]] = by_need.get(e["needs"], 0) + 1
    tier_counts = list(sh['rows_by_tier'].values())
    tiers_1_2 = tier_counts[0] + tier_counts[1]
    lines: list[str] = []
    w = lines.append

    w("# R6 calibration report — first-run R6 rows against Contract v1 (revision 3, dry run)")
    w("")
    w("*Status: **data and evidence only.** Contract v1 is not frozen and `adoption.yaml` keeps `binding: false`; no threshold in this report is adopted, no mapping was approved or rejected, "
      "R6 was not re-run, R7 was not started, and nothing in production was written. Generated by `python -m identity_resolution.calibration.build` from the committed inputs; "
      "the numbers below are not typed by hand.*")
    w("")
    w("## 0. The short version")
    w("")
    w(f"* **Recovered:** {rec['rows_total']} rows of `ice_model_crosswalk` ({rec['matcher_rows']} matcher rows: {rec['by_status_method'].get('AUTO/SERIES', 0)} AUTO, "
      f"{rec['by_status_method'].get('PROPOSED/SERIES', 0)} PROPOSED by series, {rec['by_status_method'].get('PROPOSED/NAME', 0)} PROPOSED by name; plus {rec['admin_structure_rows']} STRUCTURE proposal) "
      f"and {rec['redirects']} redirects, read-only from production. An offline replay of the legacy matcher reproduces **{rec['verification']['reproduced_exactly']} of {rec['verification']['stored_matcher_rows']}** matcher rows exactly "
      f"(candidate, status, method, reason text and the full sha256 decision fingerprint), so the legacy windows and numbers below are the run's own.")
    w(f"* **Windows matter.** {mat['stored_rows_material']} of {mat['stored_rows']} stored rows ({mat['stored_rows_material_pct']} %) change materially when the series is compared over the common observation "
      f"window instead of the legacy zero-filled window; {mat['legacy_strong_but_v1_not_strong_stored']} legacy-strong pairs are not strong on common months and "
      f"{mat['legacy_not_strong_but_v1_strong_stored']} legacy-weak pairs are strong.")
    w(f"* **Under the current non-binding v1 rules** the {sum(out['groups_all'].values())} Ice groups come out as "
      + ", ".join(f"{k} {v}" for k, v in out["groups_all"].items())
      + f". Of the {mat['legacy_auto_rows']} legacy AUTO rows, {mat['legacy_group_status_to_v1_outcome'].get('AUTO -> AUTO', 0)} stay AUTO.")
    w(f"* **Which keys can be calibrated without owner labels:** none of the {len(ents)} pending entries. What they need: "
      + "; ".join(f"{NEED_WORDS[k]} ({n})" for k, n in sorted(by_need.items(), key=lambda x: -x[1])) + ". Section 8 lists them.")
    w(f"* **Owner sheet:** `r6_owner_review.csv`, {sh['rows']} rows, ordered by your seven priorities; the first {tiers_1_2} rows "
      f"(tiers 1-2) already cover {sh['cumulative_unique_group_units_share_at_end_of_tier'][2] * 100:.1f} % of all Ice units.")
    w("")

    w("## 1. What was recovered, from where, and how it was checked")
    w("")
    w("| Source | Used | Why |\n|---|---|---|")
    w("| Original workflow artifact `ice-crosswalk-r6-7.0` (run 38064404218, 2026-10-10, artifact 11675135764, 32,422 bytes, expires 2027-01-08) | **located, not downloaded** | the sandbox network policy denies the artifact host (`productionresultssa13.blob.core.windows.net`). The artifact is the review CSV (a projection of the PROPOSED rows that the production table holds) plus the phases' JSON run summaries (counts, discovery flags); the stored rows are the evidence, and the replay below shows they are complete |")
    w("| Production `ice_model_crosswalk`, `ice_model_group_redirects`, `ice_brand_aliases` (`SELECT` only, Supabase project `ltvwzkffmpudpjfjomrg`) | **yes** | the authoritative stored result of the run |")
    w("| The matcher's own inputs: `registrations` (summed by canonical model and month), `vehicle_models`, `vehicle_brands`, `vehicle_generations` (`SELECT` only) | **yes** | to replay the legacy windows and to build the TDR side for Contract v1 |")
    w("| Archived Ice package `data/packages/2569-09/v3_M7.0/TDR_FULL_2569-09_v3_M7.0.zip` (sha256 `c558d2d4…94677d`) | **yes** | the Ice side; it is byte-equivalent to what is live (below) |")
    w("")
    w("Checks (all passed):")
    w("")
    w(f"* **No mutation.** Only `SELECT` statements were issued. The extracts are committed under `calibration/inputs/` with their sha256 in `MANIFEST.json`; the query is `inputs/EXTRACT_QUERY.sql`.")
    w(f"* **The package is what is live.** An md5 over every `(model_group_id, period, units)` cell of `ice_reg_trend` (18,385 cells) and over `ice_dims_model_group` (1,200 rows) computed in the database equals the same md5 computed from the archived package.")
    w(f"* **The inputs did not change after the run.** At extraction time (`{rec['extract_meta']['meta']['extracted_at']}`) {rec['extract_meta']['meta']['registrations_rows_created_after_run_start']} `registrations` rows were created, "
      f"{rec['extract_meta']['meta']['vehicle_models_updated_after_run_start']} `vehicle_models` and {rec['extract_meta']['meta']['vehicle_generations_updated_after_run_start']} `vehicle_generations` rows were updated after the run started (2026-10-10 15:38 UTC).")
    w(f"* **The replay is exact.** Replaying `vehreg.ice_crosswalk` unchanged on those inputs reproduces {rec['verification']['reproduced_exactly']} of {rec['verification']['stored_matcher_rows']} matcher rows "
      f"(same candidate, status, method, reason and full fingerprint) and finds no candidate for the other {rec['verification']['no_candidate_and_nothing_stored']} groups, where nothing is stored; mismatches: {rec['verification']['mismatches']}.")
    w("")

    w("## 2. The first-run R6 rows")
    w("")
    w(table(["status / method", "rows"], [[k, v] for k, v in rec["by_status_method"].items()]))
    w("")
    w(f"* {rec['groups_with_a_row']} of {rec['groups_total']} Ice groups got a row; {rec['groups_without_a_row']} found no candidate. Those {rec['groups_with_a_row']} groups hold "
      f"{pct(rec['ice_units_in_groups_with_a_row'], rec['ice_units_total'])} % of the {rec['ice_units_total']:,} Ice units; the {rec['by_status_method'].get('AUTO/SERIES', 0)} AUTO rows hold {pct(rec['ice_units_in_legacy_auto_groups'], rec['ice_units_total'])} %.")
    w(f"* The {rec['admin_structure_rows']} `PROPOSED/ADMIN` row is the STRUCTURE proposal that phase 3 created for the `mazda-mazda-cx-3` → `mazda-mazda-cx-30` split (a question, not a match). "
      f"There are no APPROVED, LOCKED or REJECTED rows: nobody has reviewed anything yet, so **there are no owner labels in the database**.")
    w(f"* Redirects: {rec['redirects']} ({', '.join(f'{k} {v}' for k, v in rec['redirects_by_type'].items())}). Split parents have no redirect (the legacy table admits only RENAME/MERGE).")
    w("")

    w("## 3. Legacy zero-filled window vs the Contract v1 common window")
    w("")
    w("The legacy matcher compared the newest 24 months **that the Ice group has a row for**, and turned every month the TDR side lacked into 0 (`build_paired_series`). Contract v1 compares only months both sources observe (a missing row is `null`, never 0), anchored on the newest month both cover.")
    w("")
    w(f"* The Ice package covers {obs['ice_coverage_months']}; TDR registrations cover {obs['tdr_registration_months']}. So **{win['window_ends_2026-09']} of {win['stored_rows']} legacy windows end in 2026-09**, a month TDR has no data for: that month is a zero on the TDR side in every one of them.")
    w(f"* {win['with_a_tdr_zero_filled_month']} of {win['stored_rows']} legacy windows contain at least one month that was zero-filled on the TDR side; {win['calendar_span_over_24']} span more than 24 calendar months because the group has holes (the window is 24 *rows*, not 24 months); {win['fewer_than_24_months']} have fewer than 24 months.")
    w("")
    w(table(["TDR zero-filled months in the legacy window", "stored rows"], [[k, v] for k, v in win["tdr_zero_filled_months_distribution"].items()]))
    w("")
    w(f"**Material change.** The {mat['definition']}.")
    w("")
    w(table(["", "rows"], [
        ["stored rows", mat["stored_rows"]], ["…with a material change", f"{mat['stored_rows_material']} ({mat['stored_rows_material_pct']} %)"],
        ["legacy AUTO rows", mat["legacy_auto_rows"]], ["…with a material change", mat["legacy_auto_rows_material"]],
        ["all candidate pairs in the dataset", mat["all_pairs"]], ["…with a material change", mat["all_pairs_material"]]]))
    w("")
    w("Reasons (a row can have several): " + ", ".join(f"{k} {v}" for k, v in sorted(mat["by_reason_not_exclusive"].items(), key=lambda x: -x[1])) + ".")
    w("")
    w("Legacy class → v1 series state, stored rows:")
    w("")
    w(table(["legacy → v1", "stored rows"], [[k, v] for k, v in mat["legacy_class_to_v1_state_stored_rows"].items()]))
    w("")
    w("*Legacy `UNDEFINED` = correlation or ratio could not be computed (a constant or empty side). v1 `UNAVAILABLE` = fewer than 6 common months, fewer than 4 joint non-zero months, fewer than 30 units on a side, or a constant side (`series.minimums.propose`). Many legacy rows were scored on a handful of units; v1 refuses to call that evidence.*")
    w("")

    w("## 4. Distributions")
    w("")
    w("Correlation (stored rows):")
    w("")
    ks = list(dist["stored_rows_legacy"]["correlation"])
    w(table(["bin", "legacy", "v1 common window"], [[k, dist["stored_rows_legacy"]["correlation"].get(k, 0), dist["stored_rows_v1"]["correlation"].get(k, 0)] for k in dict.fromkeys(ks + list(dist["stored_rows_v1"]["correlation"]))]))
    w("")
    w("Ratio = TDR units / Ice units (stored rows):")
    w("")
    ks = list(dist["stored_rows_legacy"]["ratio"])
    w(table(["bin", "legacy", "v1 common window"], [[k, dist["stored_rows_legacy"]["ratio"].get(k, 0), dist["stored_rows_v1"]["ratio"].get(k, 0)] for k in dict.fromkeys(ks + list(dist["stored_rows_v1"]["ratio"]))]))
    w("")
    w("Name relation under Contract v1 (stored rows, by legacy status):")
    w("")
    w(table(["legacy status / v1 name relation", "rows"], [[k, v] for k, v in dist["stored_rows_name_relation_by_legacy_status"].items()]))
    w("")
    w("Brand relation (stored rows): " + ", ".join(f"{k} {v}" for k, v in dist["stored_rows_v1_brand_relation"].items())
      + ". Link type of the stored candidate: " + ", ".join(f"{k} {v}" for k, v in dist["stored_rows_v1_link_candidate"].items()) + ".")
    w("")
    w("Common months and unconfirmed-gap months (stored rows, v1):")
    w("")
    w(table(["common months", "rows"], [[k, v] for k, v in dist["stored_rows_v1_common_months"].items()]))
    w("")
    w(table(["unconfirmed-gap months in the 24-month window", "rows"], [[k, v] for k, v in dist["stored_rows_v1_semantics_gap_months"].items()]))
    w("")
    cv = dist["contradiction_vs_strong_series"]
    w(f"**A strong series against a vetoing name.** {cv['pairs_STRONG_series_but_name_CONTRADICTION_or_SIBLING']} candidate pairs ({cv['of_which_in_legacy_rows']} of them legacy rows) have a STRONG common-window series but a name relation of CONTRADICTION or SIBLING; "
      "under `series_only.allow_with_name_veto: false` they are excluded. Some are right to be (a shared seasonality between two models); some are typos or renamings. Only labels can tell which:")
    w("")
    for e in cv["examples"]:
        w(f"* {e}")
    w("")

    w("## 5. Cases around each provisional boundary")
    w("")
    w("A pair is *near a boundary* when moving that one value by a plausible step could change what Contract v1 says about it. `sheet` = pairs whose group appears in the owner sheet. Examples are ordered by newest-24-month Ice units.")
    w("")
    w(table(["key", "band", "pairs", "groups", "legacy rows", "in sheet"], [[b["key"], b["band"], b["pairs"], b["groups"], b["legacy_rows"], b["in_review_sheet"]] for b in s["boundaries"]]))
    w("")
    for b in s["boundaries"]:
        if b["examples"]:
            w(f"**{b['key']}**")
            w("")
            for e in b["examples"][:6]:
                w(f"* {e}")
            w("")

    if "sensitivity" in s:
        sn = s["sensitivity"]
        w("## 6. How far the real decisions move when one provisional value moves")
        w("")
        w(f"Each row re-runs the reference evaluator on all {sn['groups']} Ice groups with **one** policy value changed in memory (nothing in the contract changes). Baseline outcomes: "
          + ", ".join(f"{k} {v}" for k, v in sn["baseline_outcomes"].items()) + ". *groups changed* = the group's outcome, target or link type differs from the baseline.")
        w("")
        rows = []
        for v in sn["variants"]:
            rows.append([("(hypothesis) " if v["hypothetical"] else "") + v["id"], v["groups_changed"], v["groups_changed_in_legacy_rows"], v["auto_gained"], v["auto_lost"],
                         ", ".join(f"{k} {n}" for k, n in v["outcomes"].items())])
        w(table(["variant", "groups changed", "…among legacy-row groups", "AUTO gained", "AUTO lost", "outcomes"], rows))
        w("")
        w("*The two `what-if` rows are hypotheses about capability data (Ice, and Ice+TDR, confirming that an absent row means zero). The contract keeps both UNKNOWN; the rows only size what an answer would unlock.*")
        w("")

    g = s["gap_composition"]
    w("### What the unconfirmed-gap cap is made of")
    w("")
    w("`SER_MISSING_ROW_SEMANTICS_UNCONFIRMED` counts every month of the 24-month window, inside both coverages, where at least one side has no row and that side's meaning of \"no row\" is unconfirmed. "
      "A month where **neither** source has a row (for example before a model launched) counts as a gap month just like a month where only one does, and a month where only TDR lacks the row stays a gap even if Ice later confirms zero. "
      f"Of the {g['strong_pairs_with_a_gap']} STRONG pairs that carry a gap:")
    w("")
    w(table(["which side lacks the row in the gap months", "STRONG pairs"], [[k, v] for k, v in g["by_composition"].items()]))
    w("")
    w(f"* Gap months in total: {g['gap_months']['both_sources_absent']} where both sources lack the row, {g['gap_months']['only_ice_absent']} only Ice, {g['gap_months']['only_tdr_absent']} only TDR.")
    w(f"* {g['strong_pairs_whose_gap_has_no_ice_only_month']} of the {g['strong_pairs_with_a_gap']} pairs have **no** Ice-only gap month: for them Ice's answer to `Q-ICE-ABSENT-ROW` alone would not lift the cap, which is why the Ice-only what-if above changes nothing and only the Ice+TDR what-if does.")
    w(f"* Of the {g['legacy_auto_rows']} legacy AUTO rows, {g['legacy_auto_rows_now_propose']} are PROPOSE under v1; {g['legacy_auto_rows_now_propose_with_the_gap_as_a_blocker']} of those carry the gap as a blocker.")
    w("")
    w("## 7. Outcomes under the current non-binding v1 rules")
    w("")
    w(f"`binding: {str(out['binding']).lower()}` — a dry run. Per Ice group (all {sum(out['groups_all'].values())}):")
    w("")
    w(table(["outcome", "groups"], [[k, v] for k, v in out["groups_all"].items()]))
    w("")
    w(table(["primary code", "groups"], [[k, v] for k, v in out["groups_all_primary_code"].items()]))
    w("")
    w(table(["review queue", "groups"], [[k, v] for k, v in out["groups_all_review_queue"].items()]))
    w("")
    w(f"* **AUTO** {out['groups_all'].get('AUTO', 0)} groups = {out['v1_auto_units_share_of_total'] * 100:.1f} % of Ice units (the legacy run's AUTO rows covered {out['legacy_auto_units_share_of_total'] * 100:.1f} %).")
    w(f"* **PROPOSE** {out['groups_all'].get('PROPOSE', 0)} groups = {out['v1_propose_units_share_of_total'] * 100:.1f} % of units; {out['v1_propose_strong_capped']} of them are STRONG-series proposals capped below AUTO, "
      f"{out['v1_propose_capped_only_by_gap']} of those **only** by the unconfirmed-gap rule (`SER_MISSING_ROW_SEMANTICS_UNCONFIRMED`). Everything that goes to a human queue is the REVIEW workload.")
    queues = out["groups_all_review_queue"]
    w(f"* **REVIEW** (a human queue) = {sum(n for q, n in queues.items() if q != 'none')} groups: " + ", ".join(f"{q} {n}" for q, n in queues.items() if q != "none")
      + f"; the other {queues.get('none', 0)} need no human step under these rules (AUTO, or nothing to match).")
    w("* Groups with a legacy row, by v1 outcome: " + ", ".join(f"{k} {v}" for k, v in out["groups_with_legacy_row"].items()) + ".")
    w("")
    w("Legacy status → v1 outcome, stored rows:")
    w("")
    w(table(["legacy → v1", "rows"], [[k, v] for k, v in out["legacy_rows_by_legacy_status_and_v1_outcome"].items()]))
    w("")
    if s["uncovered_groups_top"]:
        w("Largest groups with no candidate under either method (possible catalog gaps or naming problems; the sheet lists those with >= 100 lifetime units):")
        w("")
        w(table(["group", "name", "brand", "lifetime units", "last 24 m", "v1"], [[g["model_group_id"], g["name"], g["brand"], f"{g['lifetime_units']:,}", f"{g['last24m_units']:,}", g["v1"]] for g in s["uncovered_groups_top"]]))
        w("")

    w("## 8. Which provisional keys cannot be calibrated without owner labels")
    w("")
    w("**None of them can be settled from the machine evidence alone.** The R6 database holds no owner decision (no APPROVED / REJECTED / changed row), so there is no ground truth to measure a threshold against; "
      "the legacy `AUTO` / `PROPOSED` status is the old matcher's opinion and is never used as a label here. What each pending entry needs:")
    w("")
    rows = []
    for e in ents:
        rows.append([e["id"], e["class"], ", ".join(e["keys"]), e["needs"],
                     "" if e["max_groups_changed_by_one_step"] is None else e["max_groups_changed_by_one_step"],
                     "" if e["boundary_pairs"] is None else f"{e['boundary_pairs']} pairs / {e['boundary_groups']} groups", e["note"]])
    w(table(["entry", "class", "keys", "needs", "most groups moved by any one variant (sec. 6)", "near the boundary (sec. 5)", "what the data adds"], rows))
    w("")
    w("Reading the table: *OWNER LABELS* entries are numeric tunables the label set below can settle; *OWNER DECISION* entries are switches, lists and orders (the data can show their size of effect but not the right answer); "
      "*OWNER SIGN-OFF* are definitions. `series_absent_row_gap` is different in kind: it waits for Ice's answer to `Q-ICE-ABSENT-ROW` and for the TDR guarantees in `provider_capabilities.yaml`, then for labels. "
      "A blank \"moved\" cell means no sensitivity variant exists for that entry (a list or an order, not a number).")
    w("")

    w("## 9. What the owner needs to label, in this order")
    w("")
    w(f"`r6_owner_review.csv` has {sh['rows']} rows. The cumulative column `cumulative_unique_group_units_share` says how much of the market the rows above it already cover.")
    w("")
    w(table(["tier", "rows", "cumulative share of Ice units at the end of the tier"], [[k, v, f"{sh['cumulative_unique_group_units_share_at_end_of_tier'].get(int(k.split()[0]), 0) * 100:.1f} %"] for k, v in sh["rows_by_tier"].items()]))
    w("")
    w("Verdicts (one per row, about the candidate shown on that row): " + ", ".join(f"`{v}`" for v in RV.OWNER_VERDICTS) + ". `owner_link_type` (" + ", ".join(RV.OWNER_LINK_TYPES) + ") is the relationship you would assert; "
      "`owner_canonical_model_id` is the right TDR model when the shown one is `WRONG_TARGET` (`a+b` for a set); `owner_notes` is free text. A row with no candidate asks only whether a TDR model exists. "
      "**Nothing was copied into the owner columns**; the legacy decision sits in `legacy_r6_status` / `legacy_r6_match_method`.")
    w("")
    w("What the labels buy, from the adoption protocol (select on a training part, confirm on held-out *brands*, report precision and recall separately for AUTO and PROPOSE; the bar for any AUTO gate is \"no AUTO row the owner labels wrong\"):")
    w("")
    w(f"* **Minimum to start:** tiers 1-2 ({tiers_1_2} rows, {sh['cumulative_unique_group_units_share_at_end_of_tier'][2] * 100:.1f} % of units) plus tier 3 (known suspicious cases). "
      f"They span {sh['brands_in_tiers_1_2']} brands, {sh['brands_with_5_or_more_rows_in_tiers_1_2']} of them with 5 or more rows, so a held-out-by-brand split is possible. Top brands: "
      + ", ".join(f"{k} {v}" for k, v in sh["top_brands_in_tiers_1_2"].items()) + ".")
    w("* **Positive labels** (`CORRECT_*`) calibrate the AUTO gate and the minimums; **negative labels** (`WRONG_TARGET`, with the true model in `owner_canonical_model_id`) calibrate the name vetoes, the `decisively_wrong` bounds and the margin. "
      "A label of `INSUFFICIENT_EVIDENCE` is itself informative: it marks where no automatic rule should fire.")
    w("* **Rows near a boundary decide the value** (section 5): label those first within each tier; a threshold cannot be placed by rows far from it.")
    w("* **Not labellable yet:** the unconfirmed-gap cap (needs Ice's answer first), and any key whose class is `design_choice` (needs your decision, not data).")
    w("")

    w("## 10. Limits of this report")
    w("")
    w("* **The evaluator is a reference transcription of the SPEC, written by the same author** (`ref_eval_*.py`; it agrees with all 508 golden cases). Agreement proves consistency, not correctness; a rule that is wrong in the SPEC is wrong here.")
    w(f"* **Absent rows stay UNKNOWN** on both sides (invariant I4a). Ice has holes in {obs['ice_groups_with_absent_in_coverage_months']} of 1,200 groups (median {obs['ice_groups_absent_months_median']} absent months), TDR in most models; every such month is excluded and counted as an unconfirmed-gap month, which caps AUTO. This is why far fewer groups reach AUTO than the old matcher produced.")
    w(f"* **TDR data shape.** {obs['tdr_models_with_series']} of {obs['tdr_models']} TDR models have a registrations series; {obs['tdr_generations_with_ended_date']} of {obs['tdr_generations']} generations have an `ended` date, so the lifecycle veto can only act on launch dates; "
      f"`body_type` is populated for {obs['tdr_models_body_type_populated']} of {obs['tdr_models']} models. The last TDR month (2026-08) is a classless pivot month in the registrations pipeline (see `provider_capabilities.yaml` trace), which can understate class-dependent nameplates.")
    w("* **Volumes only order rows.** The tier cutoffs (`10,000` lifetime or `1,000` last-24-month units; `100` units for groups with no candidate; the \"material change\" tolerances) are prioritisation conventions in `review.py` / `pairs.py`, not policy.")
    w("* **A fresh evaluation, not a write plan.** The evaluator ran with no stored mappings, so it says what Contract v1 would conclude on this data, not what the write matrix would do to the existing R6 rows (that would be the I18 / protected-state logic, which has nothing to protect yet).")
    w("* **Extraction time.** The TDR side is as of 2026-10-11 02:55 UTC; the check in section 1 shows it equals the run's inputs.")
    w("* **Pairs are a selection.** The dataset keeps every legacy-stored, legacy-proposed and v1-relevant pair; plainly contradicting weak pairs are counted but not listed (`r6_calibration_groups.csv` has all 1,200 groups).")
    w("")
    return "\n".join(lines) + "\n"


def pct(a, b):
    return round(100.0 * a / b, 1) if b else 0.0
