import Link from "next/link";
import { getBrands,getEvents,getFeaturedModels,getModels } from "@/lib/data";
export const dynamic="force-dynamic";
function card(r:any){return <Link className="homeCarCard" href={`/models/${r.slug}`} key={r.id}><div>{r.image_url?<img src={r.image_url} alt={r.name_th}/>:<span>{r.brands?.name_th||"TDR"}</span>}</div><small>{r.brands?.name_th}</small><b>{r.name_th}</b><p>{[r.body_type,(r.powertrains||[]).join(" / ")].filter(Boolean).join(" · ")}</p></Link>}
export default async function Home(){const[brands,events,featured,models]=await Promise.all([getBrands(30),getEvents(5),getFeaturedModels(6),getModels(12)]);const current=(featured.length?featured:(models as any[]).filter(r=>r.status!=="discontinued").slice(0,6)) as any[];return <>
<section className="newHomeHero"><div className="newHomeCopy"><small>TDR AUTOMOTIVE INTELLIGENCE</small><h1>รถที่ขายในไทย<br/>กับอุตสาหกรรมที่อยู่ข้างหลังมัน</h1><p>แคตตาล็อกรถรุ่นปัจจุบัน รุ่นย่อย ราคา Powertrain ยอดจดทะเบียน ฐานผลิตไทย โรงงาน และข้อมูลตลาดที่ TDR จัดโครงสร้างเอง</p><div><Link className="heroPrimary" href="/models">เปิดแคตตาล็อกรถ</Link><Link className="heroSecondary" href="/production">ดูรถผลิตไทย</Link></div></div><Link href="/reports" className="reportHeroCard"><small>TDR REPORT · MEMBER PREVIEW</small><h2>ข้อมูลตลาดที่เห็น “โครงสร้าง” ไม่ใช่แค่ยอดขายรวม</h2><div className="fakePieHero"><span>Segment</span><b>••%</b></div><p>CBU / รถผลิตไทย · Origin · Powertrain · Segment share · บทวิเคราะห์</p><em>ดูตัวอย่าง Report →</em></Link></section>
<section className="homeBrandBand"><div><b>แบรนด์ในฐานข้อมูล</b><Link href="/brands">ทั้งหมด →</Link></div><div>{brands.map((b:any)=><Link href={`/brands/${b.slug}`} key={b.id}>{b.logo_url?<img src={b.logo_url} alt={b.name_th}/>:<span>{b.name_th.slice(0,2)}</span>}<small>{b.name_th}</small></Link>)}</div></section>
<section className="homeCurrent"><div className="catalogSectionHead"><div><small>CATALOG</small><h2>รถในฐานข้อมูล</h2></div><Link href="/models">ดูทั้งหมด →</Link></div><div className="homeCarGrid">{current.map(card)}</div></section>
<section className="homeBottomGrid"><div><div className="catalogSectionHead"><div><small>LATEST</small><h2>ข่าวอุตสาหกรรม</h2></div><Link href="/news">ทั้งหมด →</Link></div><div className="activityList">{events.length?events.map((e:any)=><div className="activityItem" key={e.id}><span className="activityType">{e.event_type?.toUpperCase()}</span><div><strong>{e.title_th}</strong><p>{e.summary_th||e.source_name||""}</p></div><time>{e.event_date?.slice(5)}</time></div>):<div className="publicEmpty">ยังไม่มีข่าว</div>}</div></div><div className="homeIndustryLinks"><small>INDUSTRY LAYER</small><h2>ดูรถในอีกมุม</h2><Link href="/production"><b>รถผลิตในประเทศไทย</b><span>Production program · Local content · MiT →</span></Link><Link href="/plants"><b>โรงงาน</b><span>Capacity · Utilization · รุ่นที่ผลิต →</span></Link><Link href="/reports"><b>TDR Report</b><span>Market structure · Analysis →</span></Link></div></section>
</>}
