import Link from "next/link";
import { notFound } from "next/navigation";
import { getModelBundle,getRelatedEvents,getProductionProgramsByModel,getRelatedModels,getModelRegistrationSummary } from "@/lib/data";

function launch(r:any){return[r.launch_quarter,r.launch_year].filter(Boolean).join(" ")||"—"}
function baht(n:any){return n?`฿${Number(n).toLocaleString()}`:"—"}
function ptSummary(p:any){const b:string[]=[];if(p.displacement_cc)b.push(`${Number(p.displacement_cc).toLocaleString()} cc`);if(p.battery_capacity_kwh)b.push(`${p.battery_capacity_kwh} kWh${p.battery_chemistry?` ${p.battery_chemistry}`:""}`);if(p.powertrain_type)b.push(p.powertrain_type);if(p.horsepower_ps)b.push(`${p.horsepower_ps} PS`);return b.join(" · ")||p.label||"Powertrain"}

export default async function ModelDetail({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const r:any=await getModelBundle(slug);if(!r)notFound();
  const[events,programs,related,regs]=await Promise.all([getRelatedEvents({modelId:r.id},8),getProductionProgramsByModel(r.id),getRelatedModels(r,6),getModelRegistrationSummary(r.id)]);const latestReg=regs[0];
  const ptById=new Map((r.powertrains_detail||[]).map((p:any)=>[p.id,p]));
  const currentTrims=(r.trims||[]).filter((t:any)=>t.status!=="discontinued");
  return <main className="consumerModelPage">
    <section className="consumerHero"><div className="consumerImage">{r.image_url?<img src={r.image_url} alt={r.name_th}/>:<div className="consumerImagePlaceholder"><span>{r.brands?.name_th||"TDR"}</span><b>{r.name_th}</b></div>}</div><div className="consumerHeroCopy"><small>{r.brands?.name_th||"MODEL"}</small><h1>{r.name_th}</h1><p className="generationLine">{r.generation||""}</p><div className="consumerBadges">{[r.segment,r.body_type,r.market_position,...(r.powertrains||[]),r.production_type,r.production_country,r.seats?`${r.seats} ที่นั่ง`:null].filter(Boolean).map((x:string)=><span key={x}>{x}</span>)}</div><div className="consumerPrice"><small>ราคาปัจจุบัน</small><strong>{r.retail_price_min||r.retail_price_max?(r.retail_price_min!==r.retail_price_max?`${baht(r.retail_price_min)} – ${baht(r.retail_price_max)}`:baht(r.retail_price_min||r.retail_price_max)):"ดูรุ่นย่อยด้านล่าง"}</strong></div></div></section>
    {r.consumer_description?<section className="consumerContext"><small>TDR MODEL CONTEXT</small><p>{r.consumer_description}</p></section>:null}
    <section className="consumerFacts"><div><small>เปิดตัวไทย</small><b>{launch(r)}</b></div><div><small>แหล่งผลิต</small><b>{r.production_country||"—"}</b></div><div><small>รูปแบบ</small><b>{r.production_type||"—"}</b></div><div><small>ยอดจดทะเบียนล่าสุด</small><b>{latestReg?latestReg.registrations.toLocaleString():"—"}</b>{latestReg?<em>{latestReg.period}</em>:null}</div>{r.payload_capacity_kg?<div><small>Payload</small><b>{Number(r.payload_capacity_kg).toLocaleString()} kg</b></div>:null}</section>

    <section className="consumerSection trimSection"><div className="consumerSectionHead"><div><small>TRIMS & PRICE</small><h2>รุ่นย่อยที่จำหน่าย</h2></div></div>{currentTrims.length?<div className="trimPublicList">{currentTrims.map((t:any)=>{const linked=(t.trim_powertrains||[]).map((x:any)=>x.model_powertrains||ptById.get(x.powertrain_id)).filter(Boolean);return <details key={t.id} className="trimPublicCard"><summary><div><b>{t.name}</b><span>{linked.map((p:any)=>ptSummary(p)).join(" / ")||""}</span></div><strong>{baht(t.price_baht)}</strong></summary><div className="trimPublicBody">{t.description?<p>{t.description}</p>:<p className="mutedPublic">ยังไม่มีรายละเอียดอุปกรณ์ของ Trim นี้</p>}{(t.seats_override||t.payload_capacity_kg_override)?<div className="trimOverrides">{t.seats_override?<span>{t.seats_override} ที่นั่ง</span>:null}{t.payload_capacity_kg_override?<span>Payload {t.payload_capacity_kg_override} kg</span>:null}</div>:null}</div></details>})}</div>:<p className="publicEmpty">ยังไม่ได้กรอก Trim</p>}</section>

    {(r.powertrains_detail||[]).length?<section className="consumerSection"><div className="consumerSectionHead"><div><small>POWERTRAIN DETAILS</small><h2>รายละเอียดระบบขับเคลื่อน</h2></div></div><div className="consumerPowertrainList">{r.powertrains_detail.map((p:any)=><details key={p.id}><summary><b>{p.label||ptSummary(p)}</b><span>{ptSummary(p)}</span></summary><dl><dt>ประเภท</dt><dd>{p.powertrain_type||"—"}</dd>{p.engine_code?<><dt>Engine code</dt><dd>{p.engine_code}</dd></>:null}{p.motor_output_kw?<><dt>Motor output</dt><dd>{p.motor_output_kw} kW</dd></>:null}{p.torque_nm?<><dt>แรงบิด</dt><dd>{p.torque_nm} Nm</dd></>:null}{p.transmission?<><dt>Transmission</dt><dd>{p.transmission}</dd></>:null}{p.drivetrain?<><dt>Drivetrain</dt><dd>{p.drivetrain}</dd></>:null}</dl></details>)}</div></section>:null}

    {programs.length?<Link href={`/production/${r.slug}`} className="productionBridge"><div><small>THAILAND PRODUCTION</small><h2>รุ่นนี้มีข้อมูลการผลิตในประเทศไทย</h2><p>ดูโรงงาน Platform ปริมาณผลิต Local Content MiT และบริบทของรถรุ่นนี้ในฐานะผลิตภัณฑ์อุตสาหกรรม</p></div><span>ดูข้อมูลการผลิต →</span></Link>:null}
    <section className="consumerSection"><div className="consumerSectionHead"><h2>ข่าวและอัปเดต</h2><Link href="/news">ข่าวทั้งหมด →</Link></div>{events.length?<div className="consumerNewsList">{events.map((e:any)=><article key={e.id}><time>{e.event_date}</time><div><b>{e.title_th}</b><p>{e.summary_th||e.source_name||""}</p></div></article>)}</div>:<p className="publicEmpty">ยังไม่มีข่าวที่เชื่อมกับรุ่นนี้</p>}</section>
    {related.length?<section className="consumerSection"><div className="consumerSectionHead"><h2>รถรุ่นอื่นจาก {r.brands?.name_th||"แบรนด์เดียวกัน"}</h2></div><div className="relatedCarStrip">{related.map((m:any)=><Link href={`/models/${m.slug}`} key={m.id}><div className="relatedCarVisual">{m.image_url?<img src={m.image_url} alt=""/>:<span>{m.name_th}</span>}</div><b>{m.name_th}</b><small>{[m.body_type,(m.powertrains||[]).join("/")].filter(Boolean).join(" · ")}</small></Link>)}</div></section>:null}
  </main>;
}
