import { publicDb } from "@/lib/supabase";

export async function getBrands(limit=100){const db=publicDb();if(!db)return[];const{data}=await db.from("brands").select("*").order("name_th").limit(limit);return data??[]}
export async function getBrand(slug:string){const db=publicDb();if(!db)return null;const{data}=await db.from("brands").select("*").eq("slug",slug).maybeSingle();return data??null}
export async function getModels(limit=500){const db=publicDb();if(!db)return[];const{data}=await db.from("models").select("*, brands(name_th,slug,logo_url), model_plants(plant_id,plants(name_th,slug,province,maker_group))").order("updated_at",{ascending:false}).limit(limit);return data??[]}
export async function getModel(slug:string){const db=publicDb();if(!db)return null;const{data}=await db.from("models").select("*, brands(name_th,slug,logo_url), model_plants(plant_id,plants(name_th,slug,province,maker_group))").eq("slug",slug).maybeSingle();return data??null}
export async function getFeaturedModels(limit=8){const db=publicDb();if(!db)return[];const{data}=await db.from("models").select("*, brands(name_th,slug,logo_url)").eq("featured",true).neq("status","discontinued").order("updated_at",{ascending:false}).limit(limit);return data??[]}
export async function getModelPowertrains(modelId:string){const db=publicDb();if(!db)return[];const{data}=await db.from("model_powertrains").select("*").eq("model_id",modelId).order("created_at");return data??[]}
export async function getModelTrims(modelId:string){const db=publicDb();if(!db)return[];const{data}=await db.from("trims").select("*, trim_powertrains(powertrain_id, model_powertrains(*))").eq("model_id",modelId).order("sort_order").order("created_at");return data??[]}
export async function getModelBundle(slug:string){const model:any=await getModel(slug);if(!model)return null;const[powertrains,trims]=await Promise.all([getModelPowertrains(model.id),getModelTrims(model.id)]);return{...model,powertrains_detail:powertrains,trims}}

export async function getPlants(limit=100){const db=publicDb();if(!db)return[];const{data}=await db.from("plants").select("*").order("name_th").limit(limit);return data??[]}
export async function getPlant(slug:string){const db=publicDb();if(!db)return null;const{data}=await db.from("plants").select("*").eq("slug",slug).maybeSingle();return data??null}
export async function getCompanies(limit=100){const db=publicDb();if(!db)return[];const{data}=await db.from("companies").select("*").order("name_th").limit(limit);return data??[]}
export async function getCompany(slug:string){const db=publicDb();if(!db)return null;const{data}=await db.from("companies").select("*").eq("slug",slug).maybeSingle();return data??null}

// Compatibility only. Upcoming is no longer a public category in V1.1.
export async function getUpcoming(limit=12){const db=publicDb();if(!db)return[];const{data}=await db.from("models").select("*, brands(name_th,slug)").eq("status","current").order("launch_year",{ascending:false,nullsFirst:false}).limit(limit);return data??[]}

export async function getEvents(limit=30){const db=publicDb();if(!db)return[];const{data}=await db.from("events").select("*").eq("published",true).order("event_date",{ascending:false}).limit(limit);return data??[]}
export async function getRelatedEvents(filters:{brandId?:string;modelId?:string;plantId?:string;companyId?:string},limit=20){const db=publicDb();if(!db)return[];let q=db.from("events").select("*").eq("published",true).order("event_date",{ascending:false}).limit(limit);if(filters.brandId)q=q.eq("related_brand_id",filters.brandId);if(filters.modelId)q=q.eq("related_model_id",filters.modelId);if(filters.plantId)q=q.eq("related_plant_id",filters.plantId);if(filters.companyId)q=q.eq("related_company_id",filters.companyId);const{data}=await q;return data??[]}
export async function searchAll(q:string){const db=publicDb();if(!db||!q.trim())return{brands:[],models:[],plants:[],companies:[]};const term=`%${q.trim()}%`;const[brands,models,plants,companies]=await Promise.all([db.from("brands").select("id,slug,name_th,name_en").or(`name_th.ilike.${term},name_en.ilike.${term}`).limit(10),db.from("models").select("id,slug,name_th,name_en,generation").or(`name_th.ilike.${term},name_en.ilike.${term}`).limit(10),db.from("plants").select("id,slug,name_th,name_en,province").or(`name_th.ilike.${term},name_en.ilike.${term},province.ilike.${term}`).limit(10),db.from("companies").select("id,slug,name_th,name_en,company_type").or(`name_th.ilike.${term},name_en.ilike.${term}`).limit(10)]);return{brands:brands.data??[],models:models.data??[],plants:plants.data??[],companies:companies.data??[]}}

export async function getProductionPrograms(limit=300){const db=publicDb();if(!db)return[];const{data}=await db.from("production_programs").select("*, models(id,slug,name_th,generation,segment,body_type,retail_price_min,retail_price_max,brands(name_th,slug)), plants(id,slug,name_th,province,capacity_annual,estimated_production_annual), local_content_declarations(*), mit_approvals(*)").order("updated_at",{ascending:false}).limit(limit);return data??[]}
export async function getProductionProgramsByModel(modelId:string){const db=publicDb();if(!db)return[];const{data}=await db.from("production_programs").select("*, plants(id,slug,name_th,province,capacity_annual,estimated_production_annual,utilization_estimate_year), local_content_declarations(*), mit_approvals(*)").eq("model_id",modelId).order("created_at");return data??[]}
export const getDetailedPowertrains=getModelPowertrains;

export async function getRelatedModels(model:any,limit=8){const db=publicDb();if(!db)return[];let q=db.from("models").select("id,slug,name_th,generation,segment,body_type,powertrains,image_url,retail_price_min,retail_price_max,seats,brands(name_th,slug)").neq("id",model.id).neq("status","discontinued").limit(limit);if(model.brand_id)q=q.eq("brand_id",model.brand_id);const{data}=await q.order("updated_at",{ascending:false});return data??[]}
export async function getModelRegistrationSummary(modelId:string){const db=publicDb();if(!db)return[];const{data}=await db.from("registrations").select("period,registrations").eq("model_id",modelId).order("period",{ascending:false}).limit(12);return data??[]}

export async function getPlantsWithStats(){const db=publicDb();if(!db)return[];const{data}=await db.from("plants").select("*, production_programs(id,model_id,status,annual_production_estimate,models(id,slug,name_th,generation,brands(name_th)))").order("name_th");return(data??[]).map((p:any)=>{const programs=(p.production_programs??[]).filter((x:any)=>x.status!=="ended");const estimate=p.estimated_production_annual??(programs.reduce((s:number,x:any)=>s+(x.annual_production_estimate||0),0)||null);const utilization=p.capacity_annual&&estimate?Math.round((estimate/p.capacity_annual)*1000)/10:null;return{...p,active_programs:programs,model_count:new Set(programs.map((x:any)=>x.model_id)).size,utilization_estimate:utilization,production_estimate:estimate}})}
export async function getPlantWithPrograms(slug:string){const db=publicDb();if(!db)return null;const{data}=await db.from("plants").select("*, production_programs(*, models(id,slug,name_th,generation,segment,brands(name_th)))").eq("slug",slug).maybeSingle();if(!data)return null;const programs=(data.production_programs??[]).filter((x:any)=>x.status!=="ended");const estimate=data.estimated_production_annual??(programs.reduce((s:number,x:any)=>s+(x.annual_production_estimate||0),0)||null);const utilization=data.capacity_annual&&estimate?Math.round((estimate/data.capacity_annual)*1000)/10:null;return{...data,active_programs:programs,production_estimate:estimate,utilization_estimate:utilization}}
