#!/usr/bin/env python3
"""Regenerate tests/fixtures/aion-es-market-trims.json.

The fixture is the acceptance vehicle (aion.aion_es) in exactly the shape
production stores: the rows tdr_bridge/release.py writes into
current_market_trims, whose `payload` is ProductMaster.detail() -- so the
MarketTrim columns sit under payload.specs and the resolved comparable-spec
facts under payload.comparable_specs.

It is generated rather than hand-written on purpose. A hand-written fixture
would be a second opinion about the production shape, and the bug it is meant
to catch (code reaching for payload.drivetrain, which does not exist) is
exactly the bug a wrong fixture would hide.

    python3 scripts/build-aion-es-fixture.py
"""
from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "automotive" / "vehicle_master"))

from vehreg.catalog import DATA_DIR  # noqa: E402
from vehreg.product import ProductMaster  # noqa: E402

MODEL_ID = "aion.aion_es"
YEAR = 2026


def main() -> None:
    master = ProductMaster.load(DATA_DIR, YEAR)
    rows = []
    for trim_id in sorted(
            t.id for t in master.catalog.trims.values()
            if master.catalog.model_for_trim(t.id).id == MODEL_ID):
        detail = master.detail(trim_id)
        trim = master.catalog.trims[trim_id]
        rows.append({
            "canonical_id": trim_id,
            "model_id": MODEL_ID,
            "generation_id": trim.generation_id,
            "variant_id": trim.variant_id,
            "name": trim.name,
            "powertrain": trim.powertrain.value,
            "status": "current",
            "payload": detail,
            "current_list_price": detail["current_list_price"],
            "source_refs": {k: list(v) for k, v in trim.source_refs.items()},
        })

    target = ROOT / "tests" / "fixtures" / "aion-es-market-trims.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps({
        "_comment": "Generated by scripts/build-aion-es-fixture.py from the real "
                    "canonical tree: exactly the rows tdr_bridge/release.py projects "
                    "into current_market_trims, MarketTrim columns nested under "
                    "payload.specs. Do not hand-edit.",
        "release_id": "vehicle-2026-fixture",
        "release_year": YEAR,
        "market_trims": rows,
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(rows)} trims to {target}")


if __name__ == "__main__":
    main()
