import Link from "next/link";
import { getBrands,getModels } from "@/lib/data";

function money(min:any,max:any){const f=(n:number)=>`฿${Math.round(n/1000).toLocaleString()}k`;if(!min&&!max)return"ดูรายละเอียด";if(min&&max&&min!==max)return`${f(min)}–${f(max)}`;return f(min||max)}
function Card({r}:{r:any}){return <Link className="carCatalogCard" href={`/models/${r.slug}`}><div className="carCatalogVisual">{r.image_url?<img src={r.image_url} alt={r.name_th}/>:<div className="carPlaceholder"><span>{r.brands?.name_th||"TDR"}</span><b>{r.name_th}</b></div>}</div><div className="carCatalogCopy"><small>{r.brands?.name_th||"BRAND"}</small><h3>{r.name_th}</h3><p>{[r.body_type,(r.powertrains||[]).join(" / "),r.seats?`${r.seats} ที่นั่ง`:null].filter(Boolean).join(" · ")||"ข้อมูลรุ่นรถ"}</p><div><span>{money(r.retail_price_min,r.retail_price_max)}</span><em>{r.production_type||""}</em></div></div></Link>}

export default async function ModelsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const sp=await searchParams;const[brands,all]=await Promise.all([getBrands(150),getModels(600)]);
  const current=(all as any[]).filter(r=>r.status!=="discontinued");
  const models=current.filter(r=>(!sp.brand||r.brands?.slug===sp.brand)&&(!sp.segment||r.segment===sp.segment)&&(!sp.body||r.body_type===sp.body)&&(!sp.position||r.market_position===sp.position)&&(!sp.powertrain||(r.powertrains||[]).includes(sp.powertrain))&&(!sp.production||r.production_type===sp.production));
  return <main className="catalogPage">
    <section className="catalogHero"><div><small>TDR VEHICLE CATALOG</small><h1>รถที่จำหน่ายในประเทศไทย</h1><p>รถเก๋ง SUV MPV Pickup และ light commercial รุ่นปัจจุบัน พร้อมรุ่นย่อย ราคา Powertrain ที่มา และลิงก์เข้าสู่ข้อมูลอุตสาหกรรมสำหรับรถที่ผลิตในไทย</p></div><form action="/search" className="catalogSearch"><input name="q" placeholder="ค้นหารุ่นรถ…"/><button>ค้นหา</button></form></section>
    <section className="brandRail"><div className="brandRailHead"><b>เลือกแบรนด์</b><Link href="/brands">ดูทั้งหมด →</Link></div><div className="brandLogoRail">{brands.map((b:any)=><Link href={`/models?brand=${b.slug}`} key={b.id} className="brandLogoChip">{b.logo_url?<img src={b.logo_url} alt={b.name_th}/>:<span>{b.name_th.slice(0,2).toUpperCase()}</span>}<b>{b.name_th}</b></Link>)}</div></section>
    <form className="catalogFilters"><select name="segment" defaultValue={sp.segment||""}><option value="">ทุก Segment</option>{["A","B","C","D","E"].map(x=><option key={x}>{x}</option>)}</select><select name="body" defaultValue={sp.body||""}><option value="">ทุก Body</option>{["Sedan","Hatchback","Coupe","Crossover","SUV (Monocoque)","SUV (Ladder frame)","MPV","Pickup truck","Van"].map(x=><option key={x}>{x}</option>)}</select><select name="position" defaultValue={sp.position||""}><option value="">ทุก Position</option>{["Mass","Premium","Luxury"].map(x=><option key={x}>{x}</option>)}</select><select name="powertrain" defaultValue={sp.powertrain||""}><option value="">ทุก Powertrain</option>{["ICE","HEV","PHEV","REEV","BEV"].map(x=><option key={x}>{x}</option>)}</select><select name="production" defaultValue={sp.production||""}><option value="">CBU / CKD / SKD</option>{["CBU","CKD","SKD"].map(x=><option key={x}>{x}</option>)}</select>{sp.brand?<input type="hidden" name="brand" value={sp.brand}/>:null}<button>กรอง</button><Link href="/models">ล้าง</Link></form>
    <section className="catalogAll"><div className="catalogSectionHead"><div><small>CURRENT MODELS</small><h2>รถทั้งหมด</h2></div><span>{models.length} รุ่น</span></div><div className="carCatalogGrid">{models.length?models.map((r:any)=><Card key={r.id} r={r}/>):<div className="publicEmptyCard">ไม่มีรถตรงกับตัวกรองนี้</div>}</div></section>
  </main>;
}
